server:
  port: 8080
  servlet:
    context-path: /vote/api/v1
spring:
  application:
    name: vote
  datasource:
    url: jdbc:h2:~/vote;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
      mode: always
  h2:
    console:
      enabled: false
      path: /h2
